# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Store' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Store

  pod 'PromiseKit'
  pod 'Alamofire'

  target 'StoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StoreUITests' do
    # Pods for testing
  end

end
